### ISSUE TITLE
WARNING: No tag push needed to trigger workflows

### ISSUE THREAD

**Issue by 00alia00** [NiklasEi/bevy_game_template#103]
Hi, 

I was expecting to need to push a tag before github would start charging me for runners on a private repository. Please modify the documentation to realy spell out that one needs to disable them from the gitub webpage.
You might need to make it obnoxiously loud to get the point across.

> workflow for GitHub actions creating releases for Windows, Linux, macOS, and Web (Wasm) ready for distribution
>     * the same workflow creates development builds for the mobile platforms (two separate workflows can push to the stores after [some setup](#deploy-mobile-platforms))
>     * push a tag in the form of `v[0-9]+.[0-9]+.[0-9]+*` (e.g. `v1.1.42`) to trigger the flow

thanks for the great template!
   
cheers,

Alia

**Comment by NiklasEi** [comment]
You mean the CI workflow that run on every push, right?

**Comment by 00alia00** [comment]
Yeah, I was ignorant that they would run automatically and assumed from that text that it would only happen on a version tag.
