### ISSUE TITLE
Bevy 0.14

### ISSUE THREAD

**Issue by richchurcher** [NiklasEi/bevy_game_template#116]
I always get so much use out of this template! I was thinking I might be able to take a swing at updating for Bevy 0.14, if in fact it needs much updating. However, didn't want to double up on effort you might already have started... let me know if you already have things in hand, otherwise I'll start quietly having a look at it.

**Comment by NiklasEi** [comment]
Until now I have only updated my plugins, but should get to the template today. If you want you can give it a try otherwise I will probably do it in a couple of hours.

Changes should be rather little.

**Comment by richchurcher** [comment]
Oh no problem at all! I saw your plugins were getting some updates, nope you have at it!
