### ISSUE TITLE
[Question]: Confusion about events vs ActionsPlugin & Actions resource

### ISSUE THREAD

**Issue by jmetz** [NiklasEi/bevy_game_template#122]
@NiklasEi I'm still at the initial learning phase of Bevy (which is tough as it's evolving quickly!), but I'm confused by the use of the `ActionsPlugin` here. 

I'm still confused about event passing in Bevy, but events (https://docs.rs/bevy/latest/bevy/ecs/event/trait.Event.html) seem to be best suited for this - as used in the official breakout example https://bevyengine.org/examples/games/breakout/ . What's the rationale for creating the `ActionsPlugin` and `Action` resource instead of using `Event`?  

Apologies in advance if this as a noob question :sweat_smile:

**Comment by jmetz** [comment]
Btw I added a stripped down version of your game, which uses cargo mobile2 and Events here: https://github.com/jmetz/cargo-mobile2-bevy-example

**Comment by NiklasEi** [comment]
The actions are intended to be an abstraction layer between controls and things happening in your game. If you listen for events like a keyboard button press only, you are limited to keyboard input. In most games you would want to support multiple inputs like e.g. keyboard + mouse or a controller.
It's basically a drastically simplified approach to what [leafwing-input-manager](https://github.com/Leafwing-Studios/leafwing-input-manager) does.

**Comment by jmetz** [comment]
Ah but I'm talking about `Event`s, ie not necessarily input events. In fact in the breakout example above, the event created is a `CollisionEvent` , and it's used to trigger the collision sound. To me this seems to be just like the abstraction you're describing, but one that's already built into bevy.

**Comment by NiklasEi** [comment]
Ah, you mean why not use events to communicate actions like walk/fly/jump and so on?
Events make sense for things where you are interested in changing states. Things that don't happen every frame. But in the template game I want to know the current player movement every frame, so it's easier to mutate a resource or component.

Apologies if I misunderstood the question.

**Comment by NiklasEi** [comment]
In case you don't know it yet: The Bevy Cheatbook is a nice resource and [includes a section about input mapping mentioning "actions"](https://bevy-cheatbook.github.io/input.html?highlight=action#input-mapping).
Other than that, it was mostly learning by doing in my case.
