### ISSUE TITLE
Rust Analyser + Symlink to Apps on MacOs = 🤯

### ISSUE THREAD

**Issue by ierehon1905** [NiklasEi/bevy_game_template#13]
Hello, thank you for awesome template.

I encountered issues using it with rust-analyser, it seems that it tried to analyse everything (ok) and even went through symlinks (not ok). Project could not be compiled and everything I got was:
```
Blocking waiting for file lock on build directory
```

I was able to solve the issue by deleting the symlink to `Applications`.
Is this symlink necessary?

**Comment by NiklasEi** [comment]
The link is used in macOS builds. Mac users can drag and drop the game into their Applications directory (which seems to be standard for installing mac applications).

Maybe you can tell rust-analyser to ignore the build directory? You are using VS code, right? In that case, it would be awesome if we could add a configuration preventing this problem in `.vscode`. So others don't have to figure it out again.

**Comment by NiklasEi** [comment]
If that is not possible, we could try to create the symlink during packaging instead of having it in the repository.

**Comment by ierehon1905** [comment]
Ok, so here is what I have tried unsuccessfully :( 

`.vscode/settings.json`
```json
{
  "rust-analyzer.files.excludeDirs": ["build"],
  "files.watcherExclude": {
    ...
    "**/build/macos/**": true
  }
}
```

**Comment by ierehon1905** [comment]
Oh, just found out that it may be not our fault )))

rust-analyzer/rust-analyzer/issues/7755

So...

**Comment by NiklasEi** [comment]
I just pushed a commit that removes the symlink and instead creates it only during the macOS build. Could you please verify that your issues with the symlink are now gone? Since you have access to a mac: could you please also check if [the latest macOS build](https://github.com/NiklasEi/bevy_game_template/releases/tag/v0.3.0-testing) is still installable via drag and drop to `/Applications`?

**Comment by ian-h-chamberlain** [comment]
Both the original issue seems to be gone, and I can install the test app from the `.dmg` by drag and drop to `/Applications`.

Thanks for this! I think this issue can be closed now.
