### ISSUE TITLE
What's the purpose of splitting the game in a separate lib?

### ISSUE THREAD

**Issue by IceSentry** [NiklasEi/bevy_game_template#14]
I'm not sure if it's appropriate to ask here, but I was curious what exactly is the benefit of splitting the game in it's own lib. Is it to help with compile time?

**Comment by NiklasEi** [comment]
I think the compile-time benefits are negligible for the template. In general, I prefer a lib for anything containing non-trivial logic.

* Better & easier testing
* You might want multiple binaries using the same libs (think e.g. multiplayer game sharing libs for server/client binaries)
* You could split a growing game into several libs (then you might start to get faster compile times after changes in just one of the libs)

**Comment by NiklasEi** [comment]
I'll close this for now. If you are not happy with my answer, feel free to reopen :slightly_smiling_face:

**Comment by IceSentry** [comment]
Oh sorry, forgot to close it myself, yeah, I'm happy with your answer
