### ISSUE TITLE
Requested resource does not exist on linux native

### ISSUE THREAD

**Issue by SnowyCoder** [NiklasEi/bevy_game_template#16]
Hello, I tried to clone your repo but something must have gone wrong.
Everything works fine with `cargo make serve` but when I try to run a simple `cargo run` the game crashes right after start with this error: `thread 'mainthread '' panicked at 'Requested resource does not exist: alloc::boxed::Box<dyn bevy_render::renderer::render_resource_context::RenderResourceContext>...`

Here's the full error with RUST_BACKTRACE=1 https://pastebin.com/Cs10g1Qc
`rustc --version` = `rustc 1.56.1 (59eed8a2a 2021-11-01)`
`uname -a` = `Linux snowy-pc 5.10.70-1-MANJARO #1 SMP PREEMPT Thu Sep 30 15:29:01 UTC 2021 x86_64 GNU/Linux`

**Comment by NiklasEi** [comment]
Some features need to be enabled for native. Try `cargo run --features native`.

**Comment by SnowyCoder** [comment]
Ah, I missed that, I'm sorry
