### ISSUE TITLE
Wasm builds fail

### ISSUE THREAD

**Issue by sfarmer1** [NiklasEi/bevy_game_template#19]
Thanks for making this template, but when I try to follow the steps to build for web on a fresh clone of this repo, it fails with the following output:

> Finished dev [optimized + debuginfo] target(s) in 2m 01s
>      Running `wasm-server-runner target/wasm32-unknown-unknown/debug/bevy_game.wasm`
> thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', /home/pixelartist/.cargo/registry/src/github.com-1ecc6299db9ec823/wasm-bindgen-cli-support-0.2.79/src/descriptor.rs:208:15

I get the same error when I try to use Github Actions to build this template from tags. It seems like an issue with the wasm-bindgen step?

However, I am able to build the standard Bevy examples to web just fine.

Is anyone else running into this issue? I'm running the latest version of Pop OS (Linux) and am able to build the template for Linux just fine, just not for web.

**Comment by NiklasEi** [comment]
This seems to be an issue with the latest version of wasm-bindgen-cli.
See rustwasm/wasm-bindgen#2776

**Comment by NiklasEi** [comment]
Everything works fine for me on 0.2.78
I pinned the crate to this version in the makefile for now. Let me know if that resolves the issue for you, too.

**Comment by FreddyWordingham** [comment]
Hey, great template, thanks very much for your hard work!

Getting the same issue as descirbed above, building on OSX 12.1:

```
Finished dev [optimized + debuginfo] target(s) in 2m 24s
     Running `wasm-server-runner target/wasm32-unknown-unknown/debug/bevy_game.wasm`
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', /Users/freddywordingham/.cargo/registry/src/github.com-1ecc6299db9ec823/wasm-bindgen-cli-support-0.2.79/src/descriptor.rs:208:15
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Building and running natively works no problem

**Comment by CashWasabi** [comment]
I also tested it on 0.2.79 and it works fine there, too.

**Comment by NiklasEi** [comment]
Do you still get this issue using the new web setup with `trunk`?

**Comment by NiklasEi** [comment]
With the new setup the web workflow should have improved a lot.
I'll close this for now. If you still run into issues with the new setup, feel free to open a new issue :slightly_smiling_face:
