### ISSUE TITLE
[Feature Request] iOS & Android template

### ISSUE THREAD

**Issue by maxsophya** [NiklasEi/bevy_game_template#30]
Now iOS is supported, and Android is soon to be supported, can we please get template for how to get these platforms to work?

**Comment by NiklasEi** [comment]
I am unsure if this should be in the same template or separate. I think in most cases you would either target desktop + web, or mobile devices, so I am leaning towards a second template that combines iOS and Android. What do you think?

**Comment by CleanCut** [comment]
@NiklasEi I'd rather have it all in one template, providing it was straightforward to remove stuff you don't want.

But this is your project, do it how you want! 😄

**Comment by NiklasEi** [comment]
That's good to know 🙂 
I'll just start playing around with Bevy mobile and see if I can fit it nicely into this template.

**Comment by NiklasEi** [comment]
I got Android to work :partying_face: 
It needs a bit more cleanup, but should land shortly. For iOS I currently do not have a setup and would have to rely on a contribution.

**Comment by CleanCut** [comment]
Nice!

I have iOS device(s). I'm happy to test if someone has something specific to test, but I don't have time to figure it out from scratch at the moment.

**Comment by maaku** [comment]
I have an iOS device and would be willing to put in some effort to figuring it out, but only once I can free some time to do so. I am also looking forward to the Android setup.

@NiklasEi for what it's worth, I'm developing an application which is the same across desktop/mobile/tablet. The UI is responsive, and there are some platform-specific customizations, but it is a single codebase for all. Android and iOS support is currently aspirational, however.

**Comment by NiklasEi** [comment]
I have access to a mac for a short time and added an ios setup in #61 
The app compiles fine and starts up on the simulator, but for some reason the "Play" button does not get rendered...

**Comment by NiklasEi** [comment]
#61 now runs fine for me in an iOS simulator.

It also includes release jobs for android and iOS now.

Things left for this issue:
  - [ ] Fix touch positions for the sprite movement. When touching and holding, the sprite is supposed to move to the touch position, but that position is currently off on Android and iOS simulator.
  - [ ] Verify that the release builds run on real devices for iOS and Android.
  - [ ] See if there is a way to get app bundles for Android (the APKs cannot be released via the play store).
