### ISSUE TITLE
Bevy relicensed to `Apache 2.0 OR MIT`, but this repo only acknowledges the MIT license.

### ISSUE THREAD

**Issue by Supermath101** [NiklasEi/bevy_game_template#40]
See this [Bevy PR](https://github.com/bevyengine/bevy/pull/2509). The [old license](https://github.com/NiklasEi/bevy_game_template/blob/14c329b410f2eab89962bd41a1127c05a32c5b69/credits/licenses/Bevy_MIT_License.md) is in the `credits/licenses` folder.

**Comment by NiklasEi** [comment]
Isn't the idea of `Apache 2.0` OR `MIT` that you can choose under which license you want to use Bevy? If I understand it correctly, it is fine to acknowledge only the MIT license.
Want I now realised though, is that the copyright was removed, so I'll update the license.

**Comment by janhohenheim** [comment]
@NiklasEi you got that right. I think @Supermath101 might be talking about the prospect of using Apache 2.0 instead and removing the copy of the MIT license from the credits directory to combat license bloat. At least, that's what I do to reduce the amount of files 😄

**Comment by NiklasEi** [comment]
With Apache 2.0 I would not have to include the license file? I've heard before, that I would only have to include one file if I have multiple dependencies with an Apache 2.0 license, but I couldn't find a decent source for that.
For the template as it is now, the Apache license would actually be bigger compared to using the MIT license.

**Comment by janhohenheim** [comment]
That is my understanding as well. Not an issue for me since I dual-license my code itself, so I already have an own copy of the license anyway, but since you're using CC0 this is not an option.
I see, licensing Bevy under MIT seems to be the right call here. I guess you can close this issue then?

**Comment by NiklasEi** [comment]
@Supermath101 feel free to reopen if you still see an issue here 🙂
