### ISSUE TITLE
Fresh repos copied from the template fail release workflow

### ISSUE THREAD

**Issue by janhohenheim** [NiklasEi/bevy_game_template#43]
See https://github.com/janhohenheim/test-binary/actions/runs/4093789339
Maybe the readme should mention that this option needs to be active first:
![image](https://user-images.githubusercontent.com/9047632/216794717-2cec3cb9-4a9f-48aa-bf12-edbbf8fedb90.png)
At least, I think that's what fixed it in the second release: https://github.com/janhohenheim/test-binary/actions/runs/4094004283

**Comment by NiklasEi** [comment]
Thanks for the heads-up. Just so you know, your settings change is no longer needed because the workflow now configures write access.

**Comment by janhohenheim** [comment]
TIL you can do that in the workflow itself. Cool!
