### ISSUE TITLE
Error on step `Deploy to GitHub Pages`

### ISSUE THREAD

**Issue by Siiir** [NiklasEi/bevy_game_template#47]
I have triggered the `deploy-github-page` as you instructed in your README.md in header, “Deploy web build to GitHub pages”.
Got error message on step `Deploy to GitHub Pages`.
````
Error: The deploy step encountered an error: The process '/usr/bin/git' failed with exit code 128 ❌
Notice: Deployment failed! ❌

Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```
My fork is https://github.com/Siiir/ArbiGame .

**Comment by NiklasEi** [comment]
That looks like the action does not have permission to push to your repository. Could you try to make the same changes as 0df43b9? You can also give actions write permissions for the whole repository in the settings.

**Comment by Siiir** [comment]
Adding “write permissions” worked.
