### ISSUE TITLE
No audio on iOS

### ISSUE THREAD

**Issue by NiklasEi** [NiklasEi/bevy_game_template#65]

**Comment by extrawurst** [comment]
I cannot reproduce this. audio work for me

**Comment by extrawurst** [comment]
What we should look into though is that it disables podcasts and such now instead of overlapping - this is probably a kira thing though or a config. Gotta look into it

**Comment by extrawurst** [comment]
see https://github.com/NiklasEi/bevy_kira_audio/issues/118
