### ISSUE TITLE
trunk only show black screen

### ISSUE THREAD

**Issue by Moanrisy** [NiklasEi/bevy_game_template#84]
it look running fine but why it only black screen?

I'm running natively it using cargo run working fine 
![2023-11-28T20:01:29,621626993+07:00](https://github.com/NiklasEi/bevy_game_template/assets/17421945/46515831-6511-46ef-b548-07196fcf5d06)

**Comment by KirmesBude** [comment]
For anyone else running into this:
bevy 0.12.1 added the following change https://github.com/bevyengine/bevy/pull/10623
If you add `.insert_resource(AssetMetaCheck::Never)` to your main function it should work again. (without asset preprocessing, though). You may also need to `cargo update` to actually pull in bevy 0.12.1.

https://github.com/NiklasEi/bevy_game_template/pull/79 mentions not using trunk as an alternative, but according to https://github.com/bevyengine/bevy/issues/10157#issuecomment-1802920833 this would lead to problems still if published to itch.io.

**Comment by NiklasEi** [comment]
Yes, please turn off the asset meta check. I will close this issue by turning it off by default in the template.
