### ISSUE TITLE
Mac OS release CI workflow fails: "can't find crate for `core`"

### ISSUE THREAD

**Issue by bonsairobo** [NiklasEi/bevy_game_template#87]
I'm trying to run the release CI workflow and only Mac OS fails with this error:

```
error[E0463]: can't find crate for `core`
  |
  = note: the `aarch64-apple-darwin` target may not be installed
  = help: consider downloading the target with `rustup target add aarch64-apple-darwin`

error[E0463]: can't find crate for `compiler_builtins`

For more information about this error, try `rustc --explain E0463`.
error: could not compile `cfg-if` (lib) due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
Error: Process completed with exit code 101.
```

I'm puzzled because the workflow seems to be installing the aarch64-apple-darwin target here:

```yaml
     - name: Install rust toolchain for Apple Silicon
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          targets: aarch64-apple-darwin
```

**Comment by NiklasEi** [comment]
That's quite strange. I don't have access to a Mac right now, but triggered CI to try to reproduce: https://github.com/NiklasEi/bevy_game_template/actions/runs/7153182125/job/19479340418

Is your project code available?

**Comment by bonsairobo** [comment]
@NiklasEi Yea here it is: https://github.com/bonsairobo/megadodge_mayhem

**Comment by NiklasEi** [comment]
The compile error is gone when you delete your `rust-toolchain.toml`. I guess that the target is installed for a different rust version than the one you request in the toolchain file, but I don't really understand it.

**Comment by NiklasEi** [comment]
I would consider this closed as it seemed to be a miss-configuration through the `rust-toolchain.toml` file.
Feel free to re-open if you see something that should be done about it in the template.

**Comment by bonsairobo** [comment]
I guess, although it's no uncommon for projects to commit a `rust-toolchain.toml`. Maybe there is a way to exclude it from the CI workflow.

**Comment by NiklasEi** [comment]
I will close this again. I found a couple of other rust actions that can install from `rust-toolchain.toml`, but they are all small and seem to require the file (e.g. https://github.com/dsherret/rust-toolchain-file, https://github.com/mkroening/rust-toolchain-toml). I think for the average user of this template it is simpler to not use a `rust-toolchain.toml`. If you need it, please change the action to one that supports/requires it.
