### ISSUE TITLE
trunk serve is broken

### ISSUE THREAD

**Issue by NiklasEi** [NiklasEi/bevy_game_template#99]
The trunk configuration from #90 is a proper solution to issues with absolute URLs in web builds but broke `trunk serve`, which doesn't like paths starting with a dot. Overwriting the URL in the `serve` section of `Trunk.toml` doesn't work since Trunk will add a leading "/" to the path. This should get fixed with trunk-rs/trunk#674 

Find a setup that doesn't require ugly sed commands like before #90 but works out of the box with `trunk build` and `trunk serve`.

**Comment by Plonq** [comment]
Changing the path from `./` to `/` in `Trunk.toml` fixes the issue for me (and assets still work - i.e. `/assets/audio/flying.ogg`). Am I missing something?

**Comment by NiklasEi** [comment]
Using `/` instead of `./` will break asset loading in scenarios where the app is hosted at a path other than root. This is the case for itch.io for example.

**Comment by NiklasEi** [comment]
That might work if you know the path, yes. In the case of itch you would first have to deploy a broken build to get the path (e.g. `html/5082781/`), manually fix the html file and then re-deploy. With this kind of solution, your build is only going to work on a single platform/path.
If you are OK with manual fixes, it's easier to make a search and replace to use `./` in my opinion.

**Comment by Plonq** [comment]
Fair enough, I've never deployed to Itch.io before.
IMO `/` is still a better default, with documentation RE: Itch.io deployment, rather than the other way round.
But it's up to you!

**Comment by NiklasEi** [comment]
It seems Trunk has recently fixed this. Using version `0.19.0-alpha.3` (`cargo install trunk --version 0.19.0-alpha.3`) with the following `Trunk.toml` file:
```toml
[build]
public_url = "./"
```
The serve command works properly and `trunk build` will link assets with `./` :partying_face:
I guess this was fixed in trunk-rs/trunk#717

**Comment by NiklasEi** [comment]
I'll close this issue by updating the `Trunk.toml` file once a full Trunk release works.

**Comment by NiklasEi** [comment]
Resolved with Trunk `0.19`
